import Footer from "@/components/footer";
import StickyBanner from "@/components/home/sticky-banner";
import Navbar from "@/components/navigation";
import { AuthModalProvider } from "@/context/modal-context";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
const montserrat = Montserrat({ subsets: ["vietnamese"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <AuthProvider>
          <StickyBanner />


          <AuthModalProvider>
            <Navbar />
            {children}
          </AuthModalProvider>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
